### ISSUE TITLE
Feature request - Pino support

### ISSUE THREAD

**Issue by huv1k** [axiomhq/axiom-node#94]
Hey, could you add support for [Pino](https://github.com/pinojs/pino) it's one of the core libraries that Fastify is built upon and it's a new standard for Node.js logger.

**Comment by bahlo** [comment]
Hi, official support is on our list and being worked on! I'll let you know when it's there 😎

**Comment by bahlo** [comment]
Good news, we pulled a quick one and published a Pino transport 😎 

Check it out: https://www.npmjs.com/package/@axiomhq/pino

**Comment by huv1k** [comment]
Hey, you are not exporting `import { Axiom, ClientOptions } from '@axiomhq/js';`, so it's not working correctly 🙈 you most likely forgot to publish `@axiomhq/js` with a new version. It doesn't work 
```bash
TypeError: js_1.Axiom is not a constructor
    at /Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/src/index.ts:19:17
    at step (/Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/dist/cjs/index.js:44:23)
    at Object.next (/Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/dist/cjs/index.js:25:53)
    at /Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/dist/cjs/index.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/dist/cjs/index.js:15:12)
    at axiomTransport (/Users/huv1k/Developer/04miramo/node_modules/@axiomhq/pino/dist/cjs/index.js:85:12)
    at /Users/huv1k/Developer/04miramo/node_modules/pino/lib/worker.js:15:26
    at async Promise.all (index 1)
    at module.exports (/Users/huv1k/Developer/04miramo/node_modules/pino/lib/worker.js:13:13)
```

**Comment by schehata** [comment]
@huv1k good catch 👍 I just released new versions of the libraries, should be good now, let me know if you are still facing problems.

**Comment by huv1k** [comment]
Now it works fine 🙌 thanks for pushing it 💪
